
#+TITLE: Algorítmica
#+AUTHOR: Doble Grado Ingeniería Informática y Matemáticas
#+LANGUAGE: es
#+OPTIONS: toc:nil
#+latex_header: \usepackage[spanish]{babel}
#+latex_header: \usepackage[T1]{fontenc}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage[left=2.5cm,top=2cm,right=2.5cm,bottom=2.5cm]{geometry}
#+latex_header: \usemintedstyle{manni}
#+latex_header: \setminted{linenos=true}

#+BEGIN_SRC emacs-lisp :exports results :results silent
(require 'ox-latex)
(add-to-list 'org-latex-packages-alist '("" "minted"))
(setq org-latex-listings 'minted)
(setq org-latex-pdf-process
'("pdflatex —shell-escape %f"))
#+END_SRC

* Introducción.

La ciencia de la computación es el estudio de los Algoritmos, incluyendo sus propiedades, hardware, aspectos lingüísticos y aplicaciones.

Podemos definir un */Algoritmo/* como una secuencia ordenada y finita de pasos no ambiguos tales que al llevarse a cabo, dará como resultado que se realice la tarea para la que se ha diseñado en un tiempo finito y con recursos limitados.

De esta forma, no podemos por ejemplo obtener la sucesión de /Fibonacci/ mediante un algoritmo pues esta es infinita.

/_Nota_/: Debemos tener claro que hay una diferencia entre un programa y un algoritmo. Un programa es una serie de instrucciones ordenadas codificadas en un lenguaje de programación que *expresa* un algoritmo.

** Los algoritmos.

Un algoritmo es una secuencia finita y ordenada de pasos, exentos de
ambigüedad, tal que al llevarse a cabo dará el resultado esperado a la
tarea esperada. Se resuelve con recursos limitados y tiempo finito.\\

Un método computacoinal es una cuaterna $(Q,I,\Omega,f)$ en la que $Q$ es un conjunto que contiene a $I$ y a $\Omega$ como subconjuntos y $f$ es una función de $Q$ en $Q$ tal que:
\[
f(q) = q \ \ \ \forall q \in \Omega
\]
y donde $Q$ es el conjunto de estados del cálculo, I la entrada , $\Omega$ la salida y $f$ la regla de cálculo aplicada. Cada entrada $x\in I$ define una sucesión computacionel $x_0,...,x_n$ tal que $x_0 = x$ y $x_{k+1}=f(x_k)$ si $k\geq 0$.

Se dice que la sucesión computacional termina en $k$ etapas si $k$ es el menor entero para el cual $x_k$ está en $\Omega$ y en esa caso, a partir de $x$ se obtiene como salida $x_k$.


** Propiedades de los algoritmos

Los algoritmos tienen un conjunto de propiedades comunes a todos ellos:

- *Finito.* Se puede completar en un número finito de pasos.
- *Especifidad.* Cada etapa del algoritmo está definida y descrita
  correctamente para dar respuesta a una parte determinada del
  problema. 
- *Input.* El algoritmo recibe una entrada de datos.
- *Output.* El algoritmo devuelve un resultado en base a estos datos. 
- *Efectividad.* Se completa en un tiempo determinado, que viene dado
  por el número de operaciones que se requieren para afrontar el
  problema. 

Además los algoritmos dependen tanto de sus propiedades de forma y
matemáticas, como del hardware en el que sean ejecutadas. Según el uso
que se le quiera dar al algoritmo se implementará en un lenguaje de
programación o en otro.


 
** Etapas en la elaboración de un algoritmo

1. _Expresión de algoritmos:_ Cada paso debe de describirse de manera
   clara.
2. _Validación:_ Que calcule los resultados esperados al problema
   dado. Es una frase previa a la escritura del programa.

3. _Análisis:_ Comprobar el tiempo que tardaría, así como el tamaño
   que ocuparía. Permite realizar comparaciones teóricas entre
   algoritmos.

4. _Test:_ Corrección de errores que se detecten y comparación de
   resultados.

La elección final de un algoritmo dependerá, como ya hemos dicho
antes, tanto del número de operaciones que se requieran como de los
recursos de hardware disponibles. También son otros factores a
considerar la adaptación a cualquier tipo de computador, la
simplicidad y elegancia del algoritmo y del coste económico de su
realización.\\


Un mismo algoritmo puede dar diversos tiempos en función de los datos
del problema que desee resolver, así son de especial relevancia el
tiempo en los casos mejor, peor y promedio.
