#+TITLE: Apuntes Estructura de datos.
#+AUTHOR:
#+LANGUAGE: es
#+OPTIONS: toc:nil
#+latex_header: \usepackage[spanish]{babel}
#+latex_header: \usepackage[T1]{fontenc}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage[left=2.5cm,top=2cm,right=2.5cm,bottom=2.5cm]{geometry}
#+latex_header: \usemintedstyle{manni}
#+latex_header: \setminted{linenos=true}

#+BEGIN_SRC emacs-lisp :exports results :results silent
  (require 'ox-latex)
  (add-to-list 'org-latex-packages-alist '("" "minted"))
  (setq org-latex-listings 'minted)
  (setq org-latex-pdf-process
        '("pdflatex --shell-escape %f"))
#+END_SRC
* Estructura de datos
** Tema 1 - Función de eficiencia.
El proceso que vamos a realiar es extraer la función que marca la eficiencia del código de nuestro programa.
Existe una funcion "timer" que me permite ver el tiempo que ha transcurrido en una seccion del codigo que desee.
*** Notacion O grande.
Se dice que una f(n) = O(g(n)) si a partir de un m,  f(n)<= k · g(n), donde k es una constante.
Para usar este tipo de comparación podemos utilizar simplificacion de funciones a su estructura básica.
*** Hallar la función de eficiencia.

Lo primero es dividir el codigo en trozos, y tenemos en cuenta que si:
1. Los troxos son independientes, la función de la union es O del máximo de las funciones de cada uno.
2. Los trozos son anidados o dependientes, la función de la unión es O del producto de las funciones de cada uno.

Teniendo en cuenta que cada accion cuenta como la unidad, es decir:

#+BEGIN_SRC c++
for(int i = 0; i < n; i++){
  cout << "Lmao";
}
#+END_SRC
Serian n iteraciones de valor 1. Sabiendo que la iteracion i++ tambien es una operación pero no tiene sentido tenerlo en cuenta ya que 2n = O(n), de igual forma que la asignacióndel principio del bucle, y la comparación que se realiza, es decir, contaremos las operaciones simples como una única.

** Análisis de sentencias

*** Bucles


*** Sentencias IF-ELSE

Es una sencencia en la que usamos la regla del máximo, ocurrirá el if o el else y el máximo de los 2 marca la eficiencia del bloque.

Puede ser que la condición no sea una sentencia elemental, entonces habría que tenerla en cuenta, pero si es una sentencia trivial, la sentencia será O(1)


#+BEGIN_SRC c++

if(A[0][0]== 0)
{
  for(i = 0; i < n; i++)
  {
    for(j = 0; j < n; j++)
    A[i][j] = 0;
  }
}
else
{
  for(k = 0; k < n; k++)
  {
    A[k][k] = 1;
  }
}
#+END_SRC


En este caso, tenemos que tomar máximo entre O(n^2) (lo que cuesta el if) y O(n)(lo que cuesta el else). Por ello, la eficiencia del código es O(n^2).

*** Bloques de Sentencias
En este caso, si tenemos bloques independientes se va tomando la regla del máximo para todos los bloques

*** Llamadas a funciones

Hay que mirar cuánto cuesta la llamada a la función, es muy importante para la ejecución del código.

Analizamos un ejemplo de un código de 30 líneas de las transparencias del profesor.


**** Ejemplos

 Cuando en los bucles haya i  =2, i*=4,i*=n... entonces la eficiencia será logaritmo en base n de lo que haya dentro del bucle.

