
#+latex_header: \hypersetup{colorlinks=true,linkcolor=black}

* Práctica 1

¡Reiniciar el servicio correspondiente tras los cambios en sus archivos de configuración!

** Información

*** Telnet

Para habilitar el servicio telnet hay que editar el archivo ~/etc/xinetd.d/telnet~ y cambiar la variable correspondiente.
Para que el equipo solo sea accesible desde una IP específica añadimos la línea ~only_from = <IP>~ al archivo telnet.

Para registrar los intentos de log con telnet añadimos en el archivo telnet las líneas:

+ Escoger dónde y cómo se guardarán los logs: ~log_type = FILE <file>~.\\
- Quá información guardamos de los logs fallidos: ~log_on_failure += HOST~.\\
+ Qué información guardamos de los logs válidos: ~log_on_success += HOST~.\\

*** FTP

Para que ftp no funcione en /standalone/ sino que utilice el servidio xinetd, hay que editar en ~/etc/vsftpd.conf~ y cambiar ~listen = no~. Para impedir el acceso anónimo ~anonymous_enable = no~. 
Para permitir acceder a cuentas locales descomentamos ~local_enable = yes~.\\
Para crear una lista de usuarios que se puedan conectar añadimos al fichero ~/etc/vsftpd.conf~, ~userlist_enable=YES~ ~userlist_file=/etc/vsftpd.user_list~ ~userlist_deny=NO~ Esto último significa que la lista no es para denegar acceso.
Los usuarios en cuestión deben estar escritos en el fichero ~/etc/vsftpd.user_list~.\\
Para aceptar la subida de ficheros descomentamos en el archivo ~/etc/vsftpd.conf~ la línea ~write_enable = YES~.

*** Apache

Para alterar la página de inicio cambiamos el archivo ~/var/www/index.html~.\\

El puerto se cambia en los archivos ~/etc/apache2/ports.conf~ y ~/etc/apache2/sites-enabled/000-default~.\\

Para crear unos usuarios restringidos: ~htpasswd -c <ruta/fichero usuarios restringidos> <usuario>~

En la ruta ~/var/www/<pagina restringida>.htaccess~ añadimos las líneas:

#+BEGIN_SRC ssh

AuthType Basic
AuthName "Restricted Content"
AuthUserFile "<fichero de usuarios restringidos>"
Require valid-user

#+END_SRC

Es necesario editar el archivo ~/etc/apache2/apache2.config~ y añadir las siguientes líneas:
#+BEGIN_SRC ssh

<Directory "/var/www/<pagina restringida>">
Options Indexes FollowSymLinks
AllowOverride All
Require all granted
</Directory>

#+END_SRC





